// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Login(props) {
  return JsxRuntime.jsx(JsxRuntime.Fragment, {});
}

var make = Login;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
