// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Button from "../ui/Button.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as ReactQuery from "@tanstack/react-query";

var Fetch = {};

var apiUrl = "http://localhost:8000/api/test";

function doTest(param) {
  return fetch(apiUrl).then(function (prim) {
              return prim.json();
            });
}

function Register(props) {
  var match = ReactQuery.useQuery({
        queryKey: [],
        queryFn: doTest
      });
  var tmp;
  switch (match.status) {
    case "pending" :
        tmp = "Loading...";
        break;
    case "error" :
        tmp = "Unexpected Error";
        break;
    case "success" :
        tmp = "Message is " + match.data.message;
        break;
    
  }
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("div", {
                      children: tmp
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("div", {
                              children: "Register",
                              className: "font-bold pb-3 mb-5 border-b border-accent"
                            }),
                        JsxRuntime.jsxs("form", {
                              children: [
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx("label", {
                                              children: "Username",
                                              className: "block",
                                              htmlFor: "username"
                                            }),
                                        JsxRuntime.jsx("input", {
                                              type: "text"
                                            })
                                      ]
                                    }),
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx("label", {
                                              children: "Email",
                                              className: "block",
                                              htmlFor: "email"
                                            }),
                                        JsxRuntime.jsx("input", {
                                              type: "text"
                                            })
                                      ]
                                    }),
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx("label", {
                                              children: "Password",
                                              className: "block",
                                              htmlFor: "password"
                                            }),
                                        JsxRuntime.jsx("input", {
                                              placeholder: "•••••••••",
                                              type: "password"
                                            })
                                      ]
                                    }),
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx("label", {
                                              children: "Confirm Password",
                                              className: "block",
                                              htmlFor: "confirm-password"
                                            }),
                                        JsxRuntime.jsx("input", {
                                              placeholder: "•••••••••",
                                              type: "password"
                                            })
                                      ]
                                    })
                              ],
                              className: "grid grid-cols-2 gap-4 pb-5"
                            }),
                        JsxRuntime.jsx(Button.make, {
                              type_: "submit",
                              children: "register"
                            })
                      ],
                      className: "bg-surface p-5 rounded"
                    })
              ],
              className: "bg-ground h-screen flex items-center justify-center"
            });
}

var make = Register;

export {
  Fetch ,
  apiUrl ,
  doTest ,
  make ,
}
/* Button Not a pure module */
