// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Button from "./ui/Button.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.res.mjs";

function Landing(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "Welcome to Spark Scene",
                      className: "text-2xl w-fit mx-auto mb-6"
                    }),
                JsxRuntime.jsxs("ul", {
                      children: [
                        JsxRuntime.jsx(Button.make, {
                              type_: "button",
                              onClick: (function (param) {
                                  RescriptReactRouter.push("/login");
                                }),
                              children: "Login"
                            }),
                        JsxRuntime.jsx(Button.make, {
                              type_: "button",
                              onClick: (function (param) {
                                  RescriptReactRouter.push("/register");
                                }),
                              children: "Register"
                            })
                      ],
                      className: "flex flex-col gap-6"
                    })
              ],
              className: "bg-ground h-screen"
            });
}

var make = Landing;

export {
  make ,
}
/* Button Not a pure module */
