// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.res.mjs";

function Layout(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("header", {
                      children: JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsx("div", {
                                    children: JsxRuntime.jsx("h1", {
                                          children: "Spark Scene",
                                          className: "text-xl"
                                        }),
                                    className: "flex items-center"
                                  }),
                              JsxRuntime.jsx("div", {
                                    children: JsxRuntime.jsxs("ul", {
                                          children: [
                                            JsxRuntime.jsx("li", {
                                                  children: "Dashboard",
                                                  className: "px-2 text-sm font-medium",
                                                  onClick: (function (param) {
                                                      RescriptReactRouter.push("/dashboard");
                                                    })
                                                }),
                                            JsxRuntime.jsx("li", {
                                                  children: "Users",
                                                  className: "text-sm font-medium",
                                                  onClick: (function (param) {
                                                      RescriptReactRouter.push("/users");
                                                    })
                                                })
                                          ],
                                          className: "flex flex-row gap-2"
                                        }),
                                    className: "flex items-center"
                                  })
                            ],
                            className: "flex items-center justify-between w-full px-12 py-3"
                          }),
                      className: "sticky top-0 flex-none w-full mx-auto bg-surface border-b border-accent"
                    }),
                JsxRuntime.jsx("div", {
                      children: props.children,
                      className: "w-full px-12 mx-auto"
                    })
              ],
              className: "bg-ground h-screen"
            });
}

var make = Layout;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
