// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Button(props) {
  var onClick = props.onClick;
  var onClick$1 = onClick !== undefined ? onClick : (function (param) {
        
      });
  return JsxRuntime.jsx("button", {
              children: props.children,
              className: "w-32 py-3 mx-auto bg-cyan-600 font-medium rounded-lg text-md border border-accent focus:outline-none focus:ring-gray-700 hover:bg-cyan-800",
              type: props.type_,
              onClick: onClick$1
            });
}

var make = Button;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
