// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Login from "./lib/auth/Login.res.mjs";
import * as Layout from "./lib/Layout.res.mjs";
import * as Landing from "./lib/Landing.res.mjs";
import * as Register from "./lib/auth/Register.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.res.mjs";
import * as ReactQuery from "@tanstack/react-query";

function App(props) {
  var url = RescriptReactRouter.useUrl(undefined, undefined);
  var client = new ReactQuery.QueryClient();
  var match = url.path;
  var tmp;
  var exit = 0;
  if (match) {
    var route = match.hd;
    switch (route) {
      case "login" :
          if (match.tl) {
            exit = 1;
          } else {
            tmp = JsxRuntime.jsx(Login.make, {});
          }
          break;
      case "register" :
          if (match.tl) {
            exit = 1;
          } else {
            tmp = JsxRuntime.jsx(Register.make, {});
          }
          break;
      default:
        if (match.tl) {
          exit = 1;
        } else if (route === "not-found") {
          tmp = JsxRuntime.jsx("div", {
                children: "Not Found"
              });
        } else {
          var tmp$1;
          switch (route) {
            case "dashboard" :
                tmp$1 = "Dashboard";
                break;
            case "users" :
                tmp$1 = "Users";
                break;
            default:
              RescriptReactRouter.push("/not-found");
              tmp$1 = JsxRuntime.jsx(JsxRuntime.Fragment, {});
          }
          tmp = JsxRuntime.jsx(Layout.make, {
                children: tmp$1
              });
        }
    }
  } else {
    tmp = JsxRuntime.jsx(Landing.make, {});
  }
  if (exit === 1) {
    tmp = JsxRuntime.jsx("div", {
          children: "Not Found"
        });
  }
  return JsxRuntime.jsx(ReactQuery.QueryClientProvider, {
              client: client,
              children: tmp
            });
}

var make = App;

export {
  make ,
}
/* Login Not a pure module */
